// <auto-generated />
namespace DoWhat.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_ThingHeading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_ThingHeading));
        
        string IMigrationMetadata.Id
        {
            get { return "202101222059324_added_ThingHeading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
